<?php

/**
 * BaseForestMain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property string $company
 * @property string $logo
 * @property string $url
 * @property string $position
 * @property string $location
 * @property string $description
 * @property string $how_to_apply
 * @property string $token
 * @property boolean $is_public
 * @property boolean $is_activated
 * @property string $email
 * 
 * @method string     getType()         Returns the current record's "type" value
 * @method string     getCompany()      Returns the current record's "company" value
 * @method string     getLogo()         Returns the current record's "logo" value
 * @method string     getUrl()          Returns the current record's "url" value
 * @method string     getPosition()     Returns the current record's "position" value
 * @method string     getLocation()     Returns the current record's "location" value
 * @method string     getDescription()  Returns the current record's "description" value
 * @method string     getHowToApply()   Returns the current record's "how_to_apply" value
 * @method string     getToken()        Returns the current record's "token" value
 * @method boolean    getIsPublic()     Returns the current record's "is_public" value
 * @method boolean    getIsActivated()  Returns the current record's "is_activated" value
 * @method string     getEmail()        Returns the current record's "email" value
 * @method ForestMain setType()         Sets the current record's "type" value
 * @method ForestMain setCompany()      Sets the current record's "company" value
 * @method ForestMain setLogo()         Sets the current record's "logo" value
 * @method ForestMain setUrl()          Sets the current record's "url" value
 * @method ForestMain setPosition()     Sets the current record's "position" value
 * @method ForestMain setLocation()     Sets the current record's "location" value
 * @method ForestMain setDescription()  Sets the current record's "description" value
 * @method ForestMain setHowToApply()   Sets the current record's "how_to_apply" value
 * @method ForestMain setToken()        Sets the current record's "token" value
 * @method ForestMain setIsPublic()     Sets the current record's "is_public" value
 * @method ForestMain setIsActivated()  Sets the current record's "is_activated" value
 * @method ForestMain setEmail()        Sets the current record's "email" value
 * 
 * @package    forest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForestMain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forest_main');
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('company', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('position', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('how_to_apply', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}