forest_main:
  class: sfDoctrineRouteCollection
  options:
    model:                ForestMain
    module:               main
    prefix_path:          /main
    column:               id
    with_wildcard_routes: true

show:
  class: sfDoctrineRouteCollection
  options:
    model: ForestMain
    prefix_path: /show
  url: show
  param:
    module: main
    action: show   
    
chart:
  class: sfDoctrineRouteCollection
  options:
    model: ForestMain
    prefix_path: /chart
  url: chart
  param:
    module: main
    action: chart      

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url: /
  param: { module: main, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url: /:module
  param: { action: index }

default:
  url: /:module/:action/*