<?php

/**
 * ForestMainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForestMainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForestMainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForestMain');
    }
}