<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/02/07 18:46:04
sfConfig::add(array(
  'app_sdInteractiveChart_web_dir' => '/sdInteractiveChartPlugin',
  'app_sdInteractiveChart_chart_js_url' => 'http://www.google.com/',
  'app_sdInteractiveChart_ajax_api' => 'jsapi',
  'app_sdInteractiveChart_auto_load_js' => true,
  'app_sdInteractiveChart_debug_mode' => false,
));
