<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/07 15:23:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=forest',
  'username' => 'root',
  'password' => 666,
  'name' => 'doctrine',
)),);
