<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/02/07 18:44:21
return array(

  // sdInteractiveChartPlugin_module_libs

  // sdInteractiveChartPlugin_lib
  'linegraph' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/sdLineGraph.class.php',
  'axisbasechart' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/sdAxisBaseChart.class.php',
  'basechart' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/sdBaseChart.class.php',
  'scattergraph' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/sdScatterGraph.class.php',
  'columngraph' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/sdColumnGraph.class.php',
  'piegraph' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/sdPieGraph.class.php',
  'annotatedtimelinegraph' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/rhAnnotatedTimeLineGraph.class.php',
  'areagraph' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/sdAreaGraph.class.php',
  'interactivechart' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/helper/sdInteractiveChartHelper.php',
  'sdinteractivechartconfig' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/sdInteractiveChartConfig.php',
  'gaugegraph' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/sdGaugeGraph.class.php',
  'bargraph' => '/home/fairdev/projects/diploma/plugins/sdInteractiveChartPlugin/lib/sdBarGraph.class.php',

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfwebdebugpaneldoctrine' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfwidgetformdoctrinechoice' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrineformgenerator' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'swift_doctrinespool' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecord' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinepager' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineroutecollection' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sftesterdoctrine' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinecli' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineexception' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfvalidatordoctrineunique' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfdoctrineconnectionlistener' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedatabase' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfformdoctrine' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinedqltask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinemigratetask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedropdbtask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildschematask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildtask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinedatadumptask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinedataloadtask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinebuildformstask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinegenerateadmintask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinebasetask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/fairdev/projects/diploma/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',

  // project
  'baseformfilterdoctrine' => '/home/fairdev/projects/diploma/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'forestmainformfilter' => '/home/fairdev/projects/diploma/lib/filter/doctrine/ForestMainFormFilter.class.php',
  'baseforestmainformfilter' => '/home/fairdev/projects/diploma/lib/filter/doctrine/base/BaseForestMainFormFilter.class.php',
  'baseformdoctrine' => '/home/fairdev/projects/diploma/lib/form/doctrine/BaseFormDoctrine.class.php',
  'baseforestmainform' => '/home/fairdev/projects/diploma/lib/form/doctrine/base/BaseForestMainForm.class.php',
  'forestmainform' => '/home/fairdev/projects/diploma/lib/form/doctrine/ForestMainForm.class.php',
  'baseform' => '/home/fairdev/projects/diploma/lib/form/BaseForm.class.php',

  // project_model
  'forestmain' => '/home/fairdev/projects/diploma/lib/model/doctrine/ForestMain.class.php',
  'forestmaintable' => '/home/fairdev/projects/diploma/lib/model/doctrine/ForestMainTable.class.php',
  'baseforestmain' => '/home/fairdev/projects/diploma/lib/model/doctrine/base/BaseForestMain.class.php',

  // application
  'myuser' => '/home/fairdev/projects/diploma/apps/backend/lib/myUser.class.php',

  // modules
  'main/maingeneratorconfiguration' => '/home/fairdev/projects/diploma/apps/backend/modules/main/lib/mainGeneratorConfiguration.class.php',
  'main/maingeneratorhelper' => '/home/fairdev/projects/diploma/apps/backend/modules/main/lib/mainGeneratorHelper.class.php',
);
