<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/02/07 18:44:21
sfConfig::add(array(
  'app_sdinteractivechart' => NULL,
  'app_web_dir' => '/sdInteractiveChartPlugin',
  'app_chart_js_url' => 'http://www.google.com/',
  'app_ajax_api' => 'jsapi',
  'app_auto_load_js' => true,
  'app_debug_mode' => false,
));
